"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var abc_1 = require("./abc");
var xyz_1 = require("./xyz");
(0, abc_1.display)();
(0, xyz_1.display)();
(0, abc_1.display1)();
(0, xyz_1.display2)();
console.log(abc_1.a);
console.log(xyz_1.b);
