let n:number=100;
//n="Ravi";
let fname:string ="Ravi Kumar";
let result:boolean = true;
let msg:any=100;
msg="Raj Deep";
msg=true;
console.log(n);
console.log(fname);
console.log(result);
console.log(msg);